---
title: "US COVID-19 Stats"
output:
  html_document: default
---

## Important Notes

- **DISCLAIMER**: shared with no guarantees.

- Data Sources:

  - Covidtracking, https://covidtracking.com/
  
  - USAFacts, https://usafacts.org/issues/coronavirus/

- Source code: https://github.com/mjuchem/covid19

```{r setup, echo=FALSE, include=FALSE}

library(plyr)
library(tidyverse)
library(lubridate)
library(reshape2)
library(gdata)
library(tidyquant)
library(maps)
library(RColorBrewer)
library(openxlsx)
library(gridExtra)

source("src/lib_covidtracking.R")
source("src/lib_covid_usafacts_org.R")

NVL = function(x) {
  return(ifelse(is.na(x), 0, x))
}

NIVL = function(x) {
  return(ifelse(is.na(x) | is.infinite(x), 0, x))
}

```

## Deaths per Population - Data from CDC

```{r, include=FALSE}

t <- read_tsv("data/Underlying Cause of Death, 1999-2019.txt") %>%
  mutate(Notes = NULL)

```

```{r, echo=FALSE, fig.width=12, fig.height=4}

t %>%
  ggplot(aes(x = Year, y = Deaths/Population)) +
  geom_line(color = "blue") +
  geom_text(aes(label = round(Deaths/Population * 100, digits = 2))) +
  scale_y_continuous(limits = c(0, max(t$Deaths / t$Population)), labels = scales::percent) +
  labs(
    title = "US Deaths per Population",
    x = "Year",
    caption = "CDC, http://wonder.cdc.gov/ucd-icd10.html"
  )

```

## Vaccines, Cases, Deaths - Data from OurWorldInData.org

```{r, echo=FALSE, fig.width=12, fig.height=6}

owid_covid_data <- read.csv('https://covid.ourworldindata.org/data/owid-covid-data.csv')

write.csv(owid_covid_data, 'data/owid-covid-data.csv')

owid_covid_data %>%
  filter(iso_code == 'USA') %>%
  mutate(date = ymd(date)) %>%
  ggplot(aes(x=date, y=people_vaccinated)) +
  geom_line(na.rm = TRUE, group=1, color='orange') +
  geom_line(aes(y=people_fully_vaccinated), na.rm = TRUE, group=1, color='red') +
  geom_line(aes(y=total_cases), na.rm = TRUE, group=1, color='blue') +
  geom_line(aes(y=total_deaths), na.rm = TRUE, group=1, color='black') +
  labs(
    title = 'Vaccination, Cases, Deaths',
    subtitle = 'Vaccinated (orange), Fully Vaccinated (red), Cases (blue), Deaths (black)',
    x = 'Date',
    y = '',
    caption = 'Source: OurWorldInData.org'
  ) +
  scale_y_continuous(
    # name="",
    labels = scales::comma
    ) +
  theme(
    axis.text.x = element_text(angle = 90),
    legend.position='bottom'
    )

```

## Data from Covidtracking.com

```{r data_load, echo=FALSE, include=FALSE}

t_state_usafacts.raw <- load_covid_from_usafacts_by_state()
t_states_covidtracking.raw <- load_covid_states_from_covidtracking()
t_us_covidtracking.raw <- load_covid_us_from_covidtracking()

```

```{r data_prep, echo=FALSE, include=FALSE}

USAFACTS_DATA_SOURCE <- paste0(
  "Source: USAFacts, https://usafacts.org/visualizations/coronavirus-covid-19-spread-map/",
  " (snapshot ", format(max(t_state_usafacts.raw$Date), "%m/%d/%Y"), ")."
  )

t_states_usafacts <- t_state_usafacts.raw %>%
  ddply(
    .(State, Date),
    summarize,
    COVID_confirmed = sum(COVID_confirmed),
    COVID_deaths = sum(COVID_deaths),
    population = max(population),
    COVID_death_to_population_ratio = COVID_deaths / population
  ) %>%
  mutate(
    Date.Previous = Date - 1
    )

t_states_usafacts <- t_states_usafacts %>%
  merge(
    select(t_states_usafacts, State, Date, COVID_deaths, population),
    by.x = c("State", "Date.Previous"),
    by.y = c("State", "Date")
    ) %>%
  mutate(
    COVID_deaths.delta = COVID_deaths.x - COVID_deaths.y,
    COVID_deaths.delta.corrected.population = COVID_deaths.delta / population.x,
    population = population.x,
    population.x = NULL,
    COVID_deaths = COVID_deaths.x,
    COVID_deaths.x = NULL
    ) %>%
  arrange(Date)

COVIDTRACKING_DATA_SOURCE <- paste0(
  "Source: https://covidtracking.com/",
  " (snapshot ", format(max(t_states_covidtracking.raw$date), "%m/%d/%Y"), ")."
  )

t_states_population <- t_states_usafacts %>%
  ddply(.(State), summarize, population = max(population))

t_states_covidtracking <- t_states_covidtracking.raw %>%
  merge(
    t_states_population,
    by.x = "state",
    by.y = "State"
    ) %>%
  mutate(
    totalTestResults = NVL(totalTestResults),
    positive = NVL(positive),
    hospitalized = NVL(hospitalized),
    death = NVL(death),
    population = NVL(population)
    ) %>%
  mutate(
    tests.per.population = NIVL(totalTestResults / population),
    positives.per.population = NIVL(positive / population),
    deaths.per.population = NIVL(death / population)
    )

US_POPULATION <- max(
  t_states_covidtracking %>%
    ddply(.(date), summarize, population = sum(population)) %>%
    summarize(population = max(population))
  )

t_us_covidtracking <- t_us_covidtracking.raw %>%
  mutate(
    week = week(date),
    
    death = NVL(death),
    deathIncrease = NVL(deathIncrease),
    hospitalizedCumulative = NVL(hospitalizedCumulative),
    hospitalizedIncrease = NVL(hospitalizedIncrease),
    hospitalizedCurrently = NVL(hospitalizedCurrently),
    positive = NVL(positive),
    positiveIncrease = NVL(positiveIncrease),
    negative = NVL(negative),
    totalTestResults = NVL(totalTestResults),
    totalTestResultsIncrease = NVL(totalTestResultsIncrease),
  )

t_us_covidtracking.totals <- t_us_covidtracking %>%
  filter(date == max(t_us_covidtracking$date))

US_TOTAL_TESTS <- t_us_covidtracking.totals$totalTestResults
US_TOTAL_NEGATIVE <- t_us_covidtracking.totals$negative
US_TOTAL_POSITIVE <- t_us_covidtracking.totals$positive
US_TOTAL_HOSPITALIZED <- t_us_covidtracking.totals$hospitalized
US_TOTAL_DEATHS <- t_us_covidtracking.totals$death

US_RESULTS <- paste0(
  scales::comma(US_TOTAL_TESTS), " tests, ",
  scales::comma(US_TOTAL_DEATHS), " deaths"
)

```

```{r, echo=FALSE, fig.width=10, fig.height=6}

t_us_covidtracking %>%
  arrange(date) %>%
  ggplot(mapping = aes(x = date, y = deathIncrease)) +
  geom_line() +
  geom_ma(ma_fun = EMA, n = 15, size = 2, linetype = "solid", color = "blue", alpha = .3) +
  geom_ma(ma_fun = EMA, n = 30, size = 2, linetype = "solid", color = "orange", alpha = .3) +
  scale_y_continuous(labels = scales::comma) +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
    legend.position = "bottom",
    legend.title = element_blank()
    ) +
  labs(
    title = "US COVID-19 Daily Deaths",
    subtitle = "Trends: Blue=EMA(15 days), Orange=EMA(30 days)",
    x = "",
    y = "New Deaths",
    caption = COVIDTRACKING_DATA_SOURCE
  )

```

```{r, echo=FALSE, fig.width=10, fig.height=6}

PEAK_HOSPITALIZED <- max(t_us_covidtracking$hospitalizedCurrently)
PEAK_HOSPITALIZED_DATE <- last(t_us_covidtracking %>% filter(hospitalizedCurrently == PEAK_HOSPITALIZED))$date

t_us_covidtracking %>%
  ggplot(aes(x = date, y = hospitalizedCurrently)) +
  geom_line() +
  scale_y_continuous(labels = scales::comma) +
  geom_vline(xintercept = PEAK_HOSPITALIZED_DATE, color = "grey") +
  annotate(geom = "text", x = PEAK_HOSPITALIZED_DATE, y = as.integer(PEAK_HOSPITALIZED / 3), label = paste0('Peak on ', PEAK_HOSPITALIZED_DATE), color = "red", alpha = .50, angle = 90) +
  labs(
    title = "US COVID-19 Currently Hospitalized",
    x = "Week",
    y = "# Currently Hospitalized",
    caption = COVIDTRACKING_DATA_SOURCE
  )

```

```{r, echo=FALSE, fig.width=10, fig.height=8}

PEAK_TESTS <- max(t_us_covidtracking$totalTestResultsIncrease)
PEAK_TESTS_DATE <- last(t_us_covidtracking %>% filter(totalTestResultsIncrease == PEAK_TESTS))$date

PEAK_POSITIVE <- max(t_us_covidtracking$positiveIncrease)
PEAK_POSITIVE_DATE <- last(t_us_covidtracking %>% filter(positiveIncrease == PEAK_POSITIVE))$date

PEAK_DEATHS <- max(t_us_covidtracking$deathIncrease)
PEAK_DEATHS_DATE <- last(t_us_covidtracking %>% filter(deathIncrease == PEAK_DEATHS))$date

grid.arrange(
  
  t_us_covidtracking %>%
  ggplot(mapping = aes(x = date)) +
    geom_line(aes(y = hospitalizedCurrently, color = "Currently Hospitalized")) +
    geom_line(aes(y = deathIncrease, color = "New Deaths")) +
    geom_line(aes(y = positiveIncrease, color = "New Positives")) +
    geom_line(aes(y = totalTestResultsIncrease, color = "New Tests")) +
    geom_vline(xintercept = PEAK_TESTS_DATE, color = "grey") +
    annotate(geom = "text", x = PEAK_TESTS_DATE, y = as.integer(PEAK_TESTS / 3), label = paste0('Peak on ', PEAK_TESTS_DATE), color = "red", alpha = .50, angle = 90) +
    scale_y_continuous(labels = scales::comma) +
    scale_colour_manual(values=c("orange", "red", "blue", "black")) +
    theme(
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
      legend.position = "bottom",
      legend.title = element_blank()
      ) +
    labs(
      title = "US COVID-19 - Daily",
      x = "",
      y = "# Daily Occurrences"
    ),
  
  t_us_covidtracking %>%
  ggplot(mapping = aes(x = date)) +
    geom_line(aes(y = hospitalizedCurrently, color = "Currently Hospitalized")) +
    geom_line(aes(y = deathIncrease, color = "New Deaths")) +
    geom_line(aes(y = positiveIncrease, color = "New Positives")) +
    geom_vline(xintercept = PEAK_POSITIVE_DATE, color = "grey") +
    annotate(geom = "text", x = PEAK_POSITIVE_DATE, y = as.integer(PEAK_POSITIVE / 3), label = paste0('Peak on ', PEAK_POSITIVE_DATE), color = "red", alpha = .50, angle = 90) +
    scale_y_continuous(labels = scales::comma) +
    scale_colour_manual(values=c("orange", "red", "blue")) +
    theme(
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
      legend.position = "bottom",
      legend.title = element_blank()
      ) +
    labs(
      title = "",
      x = "",
      y = "# Daily Occurrences"
    ),

  t_us_covidtracking %>%
    ggplot(mapping = aes(x = date)) +
    geom_line(aes(y = hospitalizedCurrently, color = "Currently Hospitalized")) +
    geom_line(aes(y = deathIncrease, color = "New Deaths")) +
    geom_vline(xintercept = PEAK_HOSPITALIZED_DATE, color = "grey") +
    annotate(geom = "text", x = PEAK_HOSPITALIZED_DATE, y = as.integer(PEAK_HOSPITALIZED / 3), label = paste0('Peak on ', PEAK_HOSPITALIZED_DATE), color = "red", alpha = .50, angle = 90) +
    scale_y_continuous(labels = scales::comma) +
    scale_colour_manual(values=c("orange", "red")) +
    theme(
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
      legend.position = "bottom",
      legend.title = element_blank()
      ) +
    labs(
      title = "",
      x = "",
      y = "# Daily Occurrences"
    ),

  t_us_covidtracking %>%
    ggplot(mapping = aes(x = date)) +
    geom_line(aes(y = deathIncrease, color = "New Deaths")) +
    geom_vline(xintercept = PEAK_DEATHS_DATE, color = "grey") +
    annotate(geom = "text", x = PEAK_DEATHS_DATE, y = as.integer(PEAK_DEATHS / 3), label = paste0('Peak on ', PEAK_DEATHS_DATE), color = "red", alpha = .50, angle = 90) +
    scale_y_continuous(labels = scales::comma) +
    scale_colour_manual(values=c("red")) +
    theme(
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
      legend.position = "bottom",
      legend.title = element_blank()
      ) +
    labs(
      title = "",
      x = "",
      y = "# Daily Occurrences",
      caption = COVIDTRACKING_DATA_SOURCE
    ),
  
  ncol = 2,
  nrow = 2
  
)

```

```{r, echo=FALSE, fig.width=10, fig.height=8}

grid.arrange(

  t_us_covidtracking %>%
    ggplot(mapping = aes(x = date)) +
    geom_line(aes(y = death, color = "Deaths")) +
    geom_line(aes(y = hospitalizedCumulative, color = "Hospitalizations")) +
    geom_line(aes(y = positive, color = "Positives")) +
    geom_line(aes(y = totalTestResults, color = "Tests")) +
    scale_y_continuous(labels = scales::comma) +
    scale_colour_manual(values=c("red", "orange", "blue", "black")) +
    labs(
      title = "US COVID-19 - Cumulative",
      subtitle = US_RESULTS,
      x = "",
      y = "# Cumulative Occurrences"
    ) +
    theme(
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
      legend.position = "bottom",
      legend.title = element_blank()
      ),
  
  t_us_covidtracking %>%
    ggplot(mapping = aes(x = date)) +
    geom_line(aes(y = death, color = "Deaths")) +
    geom_line(aes(y = hospitalizedCumulative, color = "Hospitalizations")) +
    geom_line(aes(y = positive, color = "Positives")) +
    scale_y_continuous(labels = scales::comma) +
    scale_colour_manual(values=c("red", "orange", "blue")) +
    labs(
      title = "",
      subtitle = "",
      x = "",
      y = "# Cumulative Occurrences",
      caption = ""
    ) +
    theme(
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
      legend.position = "bottom",
      legend.title = element_blank()
      ),

  t_us_covidtracking %>%
    ggplot(mapping = aes(x = date)) +
    geom_line(aes(y = death, color = "Deaths")) +
    geom_line(aes(y = hospitalizedCumulative, color = "Hospitalizations")) +
    scale_y_continuous(labels = scales::comma) +
    scale_colour_manual(values=c("red", "orange")) +
    labs(
      title = "",
      subtitle = "",
      x = "",
      y = "# Cumulative Occurrences",
      caption = ""
    ) +
    theme(
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
      legend.position = "bottom",
      legend.title = element_blank()
      ),

  t_us_covidtracking %>%
    ggplot(mapping = aes(x = date)) +
    geom_line(aes(y = death, color = "Deaths")) +
    scale_y_continuous(labels = scales::comma) +
    scale_colour_manual(values=c("red")) +
    labs(
      title = "",
      subtitle = "",
      x = "",
      y = "# Cumulative Occurrences",
      caption = COVIDTRACKING_DATA_SOURCE
    ) +
    theme(
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
      legend.position = "bottom",
      legend.title = element_blank()
      ),
  
  ncol = 2,
  nrow = 2

)

```

```{r, echo=FALSE, warning=FALSE, fig.width=10, fig.height=4}

grid.arrange(
  
  t_us_covidtracking %>%
    ggplot(mapping = aes(x = date)) +
    geom_line(aes(y = positive / totalTestResults), color = "blue") +
    scale_y_continuous(labels = scales::percent) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), legend.position = "none") +
    labs(
      subtitle =
        paste0("Test-to-Positive Ratio = ",
               scales::percent(US_TOTAL_POSITIVE / US_TOTAL_TESTS, accuracy = 0.01)),
      x = "",
      y = ""
    ),
  
  t_us_covidtracking %>%
    ggplot(mapping = aes(x = date)) +
    geom_line(aes(y = death / positive), color = "blue") +
    scale_y_continuous(labels = scales::percent) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), legend.position = "none") +
    labs(
      subtitle =
        paste0("Positive-to-Death Ratio = ",
               scales::percent(US_TOTAL_DEATHS / US_TOTAL_POSITIVE, accuracy = 0.01)),
      x = "",
      y = ""
    ),
  
  t_us_covidtracking %>%
    ggplot(mapping = aes(x = date)) +
    geom_line(aes(y = totalTestResults / US_POPULATION), color = "blue") +
    scale_y_continuous(labels = scales::percent) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), legend.position = "none") +
    labs(
      subtitle =
        paste0("Tests/Population Ratio = ",
               scales::percent(US_TOTAL_TESTS / US_POPULATION, accuracy = 0.01)),
      x = "",
      y = ""
    ),
  
  t_us_covidtracking %>%
    ggplot(mapping = aes(x = date)) +
    geom_line(aes(y = positive / US_POPULATION), color = "blue") +
    scale_y_continuous(labels = scales::percent) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), legend.position = "none") +
    labs(
      subtitle =
        paste0("Positive Tests/Population Ratio = ",
               scales::percent(US_TOTAL_POSITIVE / US_POPULATION, accuracy = 0.01)),
      x = "",
      y = ""
    ),

    t_us_covidtracking %>%
    ggplot(mapping = aes(x = date)) +
    geom_line(aes(y = hospitalizedCumulative / US_POPULATION), color = "blue") +
    scale_y_continuous(labels = scales::percent) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), legend.position = "none") +
    labs(
      subtitle =
        paste0("Hospitaliz./Population Ratio = ",
               scales::percent(US_TOTAL_HOSPITALIZED / US_POPULATION, accuracy = 0.01)),
      x = "",
      y = ""
    ),

  t_us_covidtracking %>%
    ggplot(mapping = aes(x = date)) +
    geom_line(aes(y = death / US_POPULATION), color = "blue") +
    scale_y_continuous(labels = scales::percent) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), legend.position = "none") +
    labs(
      subtitle =
        paste0("Deaths/Population Ratio = ",
               scales::percent(US_TOTAL_DEATHS / US_POPULATION, accuracy = 0.01)),
      x = "",
      y = "",
      caption = COVIDTRACKING_DATA_SOURCE
    ),

  nrow = 2,
  ncol = 3
  
)

```

```{r, echo=FALSE, fig.width=10, fig.height=6}

t_us_covidtracking %>%
  filter(
    week < max(week)
  ) %>%
  ddply(
    .(week),
    summarize,
    positiveIncrease = sum(positiveIncrease)
  ) %>%
  ggplot(aes(x = week, y = positiveIncrease)) +
  geom_col(fill = "grey", color = "white") +
  geom_ma(ma_fun = EMA, n = 4, size = 2, linetype = "solid", color = "orange", alpha = .3) +
  geom_ma(ma_fun = EMA, n = 8, size = 2, linetype = "solid", color = "purple", alpha = .3) +
  scale_y_continuous(labels = scales::comma) +
  labs(
    title = "US COVID-19 Weekly Tested Positive",
    subtitle = "Trends: Orange=EMA(4 weeks), Purple=EMA(8 weeks)",
    x = "Week",
    y = "New Tested Positive",
    caption = COVIDTRACKING_DATA_SOURCE
  )

```

```{r, echo=FALSE, fig.width=10, fig.height=6}

t_us_covidtracking %>%
  filter(
    week < max(week)
  ) %>%
  ddply(
    .(week),
    summarize,
    deathIncrease = sum(deathIncrease)
  ) %>%
  ggplot(aes(x = week, y = deathIncrease)) +
  geom_col(fill = "grey", color = "white") +
  geom_ma(ma_fun = EMA, n = 4, size = 2, linetype = "solid", color = "orange", alpha = .3) +
  geom_ma(ma_fun = EMA, n = 8, size = 2, linetype = "solid", color = "purple", alpha = .3) +
  scale_y_continuous(labels = scales::comma) +
  labs(
    title = "US COVID-19 Weekly Deaths",
    subtitle = "Trends: Orange=EMA(4 weeks), Purple=EMA(8 weeks)",
    x = "Week",
    y = "New Deaths",
    caption = COVIDTRACKING_DATA_SOURCE
  )

```

```{r, echo=FALSE, fig.width=10, fig.height=8}

t_states_covidtracking %>%
  ggplot(mapping = aes(x = date)) +
  geom_line(aes(y = tests.per.population, color = "Tests")) +
  geom_line(aes(y = positives.per.population, color = "Positive Results")) +
  geom_line(aes(y = deaths.per.population, color = "Deaths")) +
  scale_y_continuous(labels = scales::percent) +
  labs(
    title = "US States COVID-19 Total Tests, Positive Results, Deaths as % of State Population",
    x = "",
    y = "",
    caption = COVIDTRACKING_DATA_SOURCE
    ) +
  facet_wrap(~ state) +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```

```{r, echo=FALSE, fig.width=10, fig.height=8}

t_states_covidtracking %>%
  ggplot(mapping = aes(x = date)) +
  geom_line(aes(y = positives.per.population, color = "Positive Results")) +
  geom_line(aes(y = deaths.per.population, color = "Deaths")) +
  scale_y_continuous(labels = scales::percent) +
  labs(
    title = "US States COVID-19 Total Positive Results, Deaths as % of State Population",
    x = "",
    y = "",
    caption = COVIDTRACKING_DATA_SOURCE
    ) +
  facet_wrap(~ state) +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```

```{r, echo=FALSE, fig.width=10, fig.height=8}

t_states_covidtracking %>%
  ggplot(mapping = aes(x = date)) +
  geom_line(aes(y = deaths.per.population, color = "Deaths")) +
  scale_y_continuous(labels = scales::percent) +
  labs(
    title = "US States COVID-19 Total Deaths as % of Population",
    x = "",
    y = "",
    caption = COVIDTRACKING_DATA_SOURCE
    ) +
  facet_wrap(~ state) +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```

## Data from USAFacts.org

```{r charts_usafacts, echo=FALSE, fig.width=10, fig.height=6}

t_states_usafacts %>%
  ddply(.(Date), summarize, COVID_deaths.delta = sum(COVID_deaths.delta)) %>%
  ggplot(mapping = aes(x = Date, y = COVID_deaths.delta)) +
  geom_line() +
  # geom_col(fill = "grey", color = "white") +
  geom_ma(ma_fun = EMA, n = 15, size = 2, linetype = "solid", color = "blue", alpha = .3) +
  geom_ma(ma_fun = EMA, n = 30, size = 2, linetype = "solid", color = "orange", alpha = .3) +
  labs(
    title = "US COVID-19 Daily Deaths",
    subtitle = "Trends: Blue=EMA(15 days), Orange=EMA(30 days)",
    x = "Date",
    y = "# Daily Deaths",
    caption = USAFACTS_DATA_SOURCE
  )

```

```{r, echo=FALSE, fig.width=10, fig.height=6}

t_states_usafacts %>%
  filter(Date == max(Date)) %>%
  ggplot() +
  geom_col(mapping = aes(x = reorder(State, -COVID_deaths), y = COVID_deaths)) +
  scale_y_continuous(labels = scales::comma) +
  labs(
    title = "US States COVID-19 Total Deaths",
    x = "State",
    y = "# Deaths",
    caption = USAFACTS_DATA_SOURCE
    ) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```

```{r, echo=FALSE, fig.width=10, fig.height=6}

t_states_usafacts %>%
  filter(Date == max(Date)) %>%
  ggplot() +
  geom_col(mapping = aes(x = reorder(State, -COVID_death_to_population_ratio), y = COVID_death_to_population_ratio)) +
  scale_y_continuous(labels = scales::percent) +
  labs(
    title = "US States COVID-19 Total Deaths Corrected for State Population",
    x = "State",
    y = "Deaths corrected for population",
    caption = USAFACTS_DATA_SOURCE
    ) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```

```{r, echo=FALSE, fig.width=10, fig.height=8}

t_states_usafacts %>%
  ggplot(mapping = aes(x = Date, y = COVID_deaths.delta)) +
  geom_line() +
  scale_y_continuous(labels = scales::comma) +
  labs(
    title = "US States COVID-19 Daily Deaths",
    x = "",
    y = "# Daily Deaths",
    caption = USAFACTS_DATA_SOURCE
  ) +
  facet_wrap(~ State) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```

```{r, echo=FALSE, fig.width=10, fig.height=8}

t_states_usafacts %>%
  ggplot(mapping = aes(x = Date, y = COVID_deaths.delta.corrected.population)) +
  geom_line() +
  scale_y_continuous(labels = scales::percent) +
  labs(
    title = "US States COVID-19 Daily Deaths Corrected for State Population",
    x = "",
    y = "# Daily Deaths as a % of the Population",
    caption = USAFACTS_DATA_SOURCE
  ) +
  facet_wrap(~ State) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```

## Data from CDC.gov

```{r, echo=FALSE, warning=FALSE, include=FALSE}

# Source: https://data.cdc.gov/Health-Statistics/Deaths-from-Pneumonia-and-Influenza-P-I-and-all-de/pp7x-dyj2

CDC_PnI_URL <- "https://data.cdc.gov/api/views/pp7x-dyj2/rows.csv?accessType=DOWNLOAD&bom=true&format=true"

df <- read_csv(CDC_PnI_URL)

```

```{r, echo=FALSE, fig.width=12, fig.height=6}

t <- df %>%
  filter(
    geoid == "National",
    `MMWR Year/Week` > "201701"
    ) %>%
  ddply(.(`MMWR Year/Week`), summarize,
          `Deaths from influenza` = sum(`Deaths from influenza`),
          `Deaths from pneumonia` = sum(`Deaths from pneumonia`),
          `Deaths from pneumonia and influenza` = sum(`Deaths from pneumonia and influenza`)
        )

t %>%
  ggplot(aes(x = `MMWR Year/Week`)) +
  geom_line(aes(y = `Deaths from influenza`, color = "Influenza")) +
  geom_line(aes(y = `Deaths from pneumonia`, color = "Pneumonia")) +
  geom_line(aes(y = `Deaths from pneumonia and influenza`, color = "Pneumonia & Influenza")) +
  labs(
    title = "CDC Pneumonia & Influenza Deaths",
    subtitle = paste0("Weekly - as of April 5, 2019 - Last weekly datapoint: ", max(t$`MMWR Year/Week`)),
    caption = "Source: CDC"
  )

```

--

**DISCLAIMER**: shared with no guarantees.
